---
- name: Download t-rex mining software to /tmp/t-rex-miner.tar.gz
  get_url:
    url: "{{ t_rex_miner_url }}"
    dest: /tmp/t-rex-miner.tar.gz
    owner: root
    group: root
    mode: 0755

- name: Make sure directory for mining software exists
  file:
    path: /opt/t-rex-miner
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Unarchive downloaded software to /opt/t-rex-miner
  unarchive:
    remote_src: yes
    src: /tmp/t-rex-miner.tar.gz
    dest: /opt/t-rex-miner
    owner: root
    group: root
    mode: 0755

- name: Render unit file for mining process
  template:
    src: etc/systemd/system/hq-hashrabbit_service.j2
    dest: /etc/systemd/system/hq-hashrabbit.service
    owner: root
    group: root
    mode: 0644
  notify: restart hq-hashrabbit
